#ifndef LLAMP_H
#define LLAMP_H

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * NUL-terminated crate version. The caller does not free this pointer.
 */
const char *llamp_version(void);

#endif  /* LLAMP_H */
