[package]
name = "llamp-source-local"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
llamp-library = { path = "../../crates/llamp-library" }
llamp-plugin-api = { path = "../../crates/llamp-plugin-api" }
